# Generated by Django 4.0.4 on 2022-06-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Explanation',
            new_name='title',
        ),
    ]
